services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: >
      /bin/sh -c "ollama serve &
        sleep 5 &&
        ollama pull ${AI_MODEL} &&
        wait"

  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - ollama
    environment:
      - OLLAMA_MODEL=${AI_MODEL}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  ollama_data: