services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama 

  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    privileged: true
    env_file:
      - .env
    devices:
      - "/dev/snd:/dev/snd"
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"

volumes:
  ollama_data: