services:
  app:
    command: ["-m", "fastapi", "run", "src/main.py", "--port", "8000", "--reload"]
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./main.py
          target: /app/main.py
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock